// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnjRusQYdge9QOezdbViu_RiWAA8MJLQQ',
    appId: '1:480647896675:web:8623496d08a70f59a96256',
    messagingSenderId: '480647896675',
    projectId: 'socialmedia-e7b0a',
    authDomain: 'socialmedia-e7b0a.firebaseapp.com',
    storageBucket: 'socialmedia-e7b0a.firebasestorage.app',
    measurementId: 'G-N1SBXE5EV5',
    databaseURL: 'https://socialmedia-e7b0a-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXNZK7SQ2tid0kPMFSAngow2J8Xri-T6w',
    appId: '1:480647896675:android:fe392c12a363d687a96256',
    messagingSenderId: '480647896675',
    projectId: 'socialmedia-e7b0a',
    storageBucket: 'socialmedia-e7b0a.firebasestorage.app',
    databaseURL: 'https://socialmedia-e7b0a-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtC2FMbs3pBPxv44RvxeSGaplOCqakWH0',
    appId: '1:480647896675:ios:230b16aac0bbc20ca96256',
    messagingSenderId: '480647896675',
    projectId: 'socialmedia-e7b0a',
    storageBucket: 'socialmedia-e7b0a.firebasestorage.app',
    databaseURL: 'https://socialmedia-e7b0a-default-rtdb.firebaseio.com',
    androidClientId:
        '480647896675-hm5psqhvf7vt51qfft4tkj0q5cloke06.apps.googleusercontent.com',
    iosBundleId: 'com.cgoogle.googlechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtC2FMbs3pBPxv44RvxeSGaplOCqakWH0',
    appId: '1:480647896675:ios:230b16aac0bbc20ca96256',
    messagingSenderId: '480647896675',
    projectId: 'socialmedia-e7b0a',
    storageBucket: 'socialmedia-e7b0a.firebasestorage.app',
    databaseURL: 'https://socialmedia-e7b0a-default-rtdb.firebaseio.com',
    androidClientId:
        '480647896675-hm5psqhvf7vt51qfft4tkj0q5cloke06.apps.googleusercontent.com',
    iosBundleId: 'com.cgoogle.googlechat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnjRusQYdge9QOezdbViu_RiWAA8MJLQQ',
    appId: '1:480647896675:web:ee1848cf5e01f2b8a96256',
    messagingSenderId: '480647896675',
    projectId: 'socialmedia-e7b0a',
    authDomain: 'socialmedia-e7b0a.firebaseapp.com',
    storageBucket: 'socialmedia-e7b0a.firebasestorage.app',
    measurementId: 'G-F4FY2CKPW1',
    databaseURL: 'https://socialmedia-e7b0a-default-rtdb.firebaseio.com',
  );
}
